version: '3.5'
services:
  postgres:
    image: postgres:latest
    container_name: taskmngr_postgres_container
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  postgres:
  mongodata: